channels:
  - conda-forge
  - astropy
dependencies:
  - python==3.10
  # infrastructure
  - pip
  - ipython
  - matplotlib
  # scientific computing
  - numpy >= 1.14.2
  - scipy >= 1.1.0
  - h5py
  - astropy
  # inference
  - corner
  - emcee
  - dynesty
  - pip:
    - fsps
    - astro-sedpy >= 0.3.0
