name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: "py${{ matrix.python-version }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Clone fsps
        uses: actions/checkout@v4
        with:
          repository: cconroy20/fsps
          path: fsps
      - name: Install dependencies
        run: |
          python -m pip install -U pip pytest
          python -m pip install -U fsps astro-sedpy astropy
          python -m pip install -U scipy
          python -m pip install -U dynesty
          python -m pip install .
        env:
          SPS_HOME: ${{ github.workspace }}/fsps
      - name: Run tests
        run: python -m pytest --durations=0 --maxfail=1 -vs tests/
        env:
          SPS_HOME: ${{ github.workspace }}/fsps
