name: Tests
on:
  push:
    branches: [main, v2.0]
  pull_request:
    branches: [main, v2.0]

jobs:
  tests:
    name: "py${{ matrix.python-version }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9"]
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Clone the repo
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Clone fsps
        uses: actions/checkout@v2
        with:
          repository: cconroy20/fsps
          path: fsps
      - name: Install dependencies
        run: |
          python -m pip install -U pip pytest
          python -m pip install -U fsps astro-sedpy astropy
          python -m pip install -U six dynesty
          python -m pip install .
        env:
          SPS_HOME: ${{ github.workspace }}/fsps
      - name: Run tests
        run: python -m pytest --durations=0 --maxfail=1 -vs tests/
        env:
          SPS_HOME: ${{ github.workspace }}/fsps
